#!/usr/bin/env python3
"""Build a canonical codebook for manual ICML 2026 review fields."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"


ROWS = [
    {
        "table": "paper_notes",
        "field": "paper_read_status",
        "allowed_value": "abstract_only",
        "counts_as_review": "yes",
        "meaning": "Only abstract/title/metadata were checked; use only for triage.",
        "when_to_use": "Use when the PDF was not opened but the paper remains in the sprint.",
        "promotion_effect": "Counts as a started note, but is weak evidence for claim promotion.",
    },
    {
        "table": "paper_notes",
        "field": "paper_read_status",
        "allowed_value": "skimmed",
        "counts_as_review": "yes",
        "meaning": "Main paper was skimmed but not fully checked.",
        "when_to_use": "Use after checking intro/method/results enough to summarize the contribution.",
        "promotion_effect": "Counts as a note; reviewer should mark evidence_strength conservatively.",
    },
    {
        "table": "paper_notes",
        "field": "paper_read_status",
        "allowed_value": "read_main",
        "counts_as_review": "yes",
        "meaning": "Main paper body was read; appendix may remain unchecked.",
        "when_to_use": "Default target for sprint review.",
        "promotion_effect": "Good enough for most claim/area overlay decisions.",
    },
    {
        "table": "paper_notes",
        "field": "paper_read_status",
        "allowed_value": "read_full",
        "counts_as_review": "yes",
        "meaning": "Main paper and relevant appendix/artifact details were checked.",
        "when_to_use": "Use for artifact, theory, benchmark, or controversial claim examples.",
        "promotion_effect": "Strongest paper-note status.",
    },
    {
        "table": "paper_notes",
        "field": "paper_read_status",
        "allowed_value": "blocked",
        "counts_as_review": "yes",
        "meaning": "Paper could not be reviewed because source access or content was unavailable.",
        "when_to_use": "Use only with a reason in paper_note.",
        "promotion_effect": "Does not support promotion.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "new_problem",
        "counts_as_review": "yes",
        "meaning": "Paper primarily opens or reframes a problem.",
        "when_to_use": "Use when contribution is mostly problem definition, benchmark framing, or position.",
        "promotion_effect": "Can support trend/fault-line claims but not necessarily method-strength claims.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "new_method",
        "counts_as_review": "yes",
        "meaning": "Paper introduces a new mechanism, algorithm, architecture, or training recipe.",
        "when_to_use": "Use when the technical mechanism is the main contribution.",
        "promotion_effect": "Can support method-centered synthesis claims.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "stronger_theory",
        "counts_as_review": "yes",
        "meaning": "Paper primarily contributes theorem/proof/analysis strength.",
        "when_to_use": "Use for theory or formal-analysis papers.",
        "promotion_effect": "Useful for program-attention and theory-area claims.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "better_system",
        "counts_as_review": "yes",
        "meaning": "Paper primarily improves efficiency, scale, tooling, or systems integration.",
        "when_to_use": "Use for infrastructure, serving, tooling, or agent workflow papers.",
        "promotion_effect": "Useful for systems/agentic workload claims.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "benchmark_package",
        "counts_as_review": "yes",
        "meaning": "Paper primarily contributes benchmark/data/evaluation packaging.",
        "when_to_use": "Use when benchmark/data are central rather than a side artifact.",
        "promotion_effect": "Can support public-attention or reproducibility claims with caveats.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "incremental",
        "counts_as_review": "yes",
        "meaning": "Contribution appears mostly incremental relative to cited baselines.",
        "when_to_use": "Use when evidence does not justify headline-example status.",
        "promotion_effect": "Usually weakens headline use.",
    },
    {
        "table": "paper_notes",
        "field": "novelty_judgment",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Reviewer cannot confidently classify novelty.",
        "when_to_use": "Use when the paper needs a second read or specialist review.",
        "promotion_effect": "Blocks promotion unless other reviewed rows are strong.",
    },
    {
        "table": "paper_notes",
        "field": "evidence_strength",
        "allowed_value": "strong",
        "counts_as_review": "yes",
        "meaning": "Claim is backed by credible baselines, metrics, ablations, and limitations.",
        "when_to_use": "Use when evidence would survive direct citation in a report.",
        "promotion_effect": "Good candidate for support_rows when claim implication supports the claim.",
    },
    {
        "table": "paper_notes",
        "field": "evidence_strength",
        "allowed_value": "moderate",
        "counts_as_review": "yes",
        "meaning": "Evidence is useful but has gaps or limited scope.",
        "when_to_use": "Default for credible but not definitive papers.",
        "promotion_effect": "Can support claims with caveats.",
    },
    {
        "table": "paper_notes",
        "field": "evidence_strength",
        "allowed_value": "weak",
        "counts_as_review": "yes",
        "meaning": "Evidence is thin, undercompared, or mostly qualitative.",
        "when_to_use": "Use when paper should be a caveat or low-confidence example.",
        "promotion_effect": "Usually should not count as strong support.",
    },
    {
        "table": "paper_notes",
        "field": "evidence_strength",
        "allowed_value": "negative_or_mixed",
        "counts_as_review": "yes",
        "meaning": "Evidence complicates, narrows, or contradicts a simple claim.",
        "when_to_use": "Use when results show limits, failure modes, or mixed outcomes.",
        "promotion_effect": "May become a weakening row or caveat example.",
    },
    {
        "table": "paper_notes",
        "field": "evidence_strength",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Evidence could not be classified.",
        "when_to_use": "Use when source did not provide enough information in checked sections.",
        "promotion_effect": "Blocks promotion for that row.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "none",
        "counts_as_review": "yes",
        "meaning": "No artifact link or release was found.",
        "when_to_use": "Use after checking metadata/PDF sufficiently.",
        "promotion_effect": "Weakens artifact-visibility claims when a release is expected.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "linked_unchecked",
        "counts_as_review": "yes",
        "meaning": "Artifact link exists but was not opened or inspected.",
        "when_to_use": "Use only as a triage state.",
        "promotion_effect": "Does not satisfy artifact check gates.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "live_checked",
        "counts_as_review": "yes",
        "meaning": "Artifact/repository link was opened and exists.",
        "when_to_use": "Use after checking live status, license/release details optional.",
        "promotion_effect": "Counts toward artifact inspection but not runnable status.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "runnable",
        "counts_as_review": "yes",
        "meaning": "Artifact appears runnable or includes clear reproduction instructions.",
        "when_to_use": "Use only after inspecting repository contents.",
        "promotion_effect": "Strongest artifact support.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "broken",
        "counts_as_review": "yes",
        "meaning": "Artifact link is stale, private, missing, or unusable.",
        "when_to_use": "Use after a direct check.",
        "promotion_effect": "Weakens artifact/reproducibility claims.",
    },
    {
        "table": "paper_notes",
        "field": "artifact_status_checked",
        "allowed_value": "not_applicable",
        "counts_as_review": "yes",
        "meaning": "Artifact is not expected for this paper type.",
        "when_to_use": "Use for pure theory/position papers or cases where release is irrelevant.",
        "promotion_effect": "Neutral for artifact claims.",
    },
    {
        "table": "paper_notes",
        "field": "taxonomy_correction",
        "allowed_value": "keep",
        "counts_as_review": "yes",
        "meaning": "Current area/subarea assignment is acceptable.",
        "when_to_use": "Use when taxonomy evidence matches the paper's main contribution.",
        "promotion_effect": "Helps satisfy taxonomy gates.",
    },
    {
        "table": "paper_notes",
        "field": "taxonomy_correction",
        "allowed_value": "relabel_area",
        "counts_as_review": "yes",
        "meaning": "Paper belongs in a different report-level area.",
        "when_to_use": "Use for clear area mismatch.",
        "promotion_effect": "Blocks taxonomy-sensitive claim promotion until resolved.",
    },
    {
        "table": "paper_notes",
        "field": "taxonomy_correction",
        "allowed_value": "relabel_subarea",
        "counts_as_review": "yes",
        "meaning": "Area is acceptable but subarea should change.",
        "when_to_use": "Use for boundary or submode corrections.",
        "promotion_effect": "Caveat for subarea-level claims.",
    },
    {
        "table": "paper_notes",
        "field": "taxonomy_correction",
        "allowed_value": "split_boundary",
        "counts_as_review": "yes",
        "meaning": "Paper genuinely spans multiple areas/subareas.",
        "when_to_use": "Use when no single assignment is clearly dominant.",
        "promotion_effect": "Use as a caveat for aggregate area claims.",
    },
    {
        "table": "paper_notes",
        "field": "taxonomy_correction",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Taxonomy cannot be decided from reviewed material.",
        "when_to_use": "Use when reviewer needs more context.",
        "promotion_effect": "Blocks taxonomy-sensitive promotion.",
    },
    {
        "table": "paper_notes",
        "field": "final_report_use",
        "allowed_value": "headline_example",
        "counts_as_review": "yes",
        "meaning": "Paper can anchor a report claim.",
        "when_to_use": "Use only when contribution and evidence are clear.",
        "promotion_effect": "Strong candidate for final narrative.",
    },
    {
        "table": "paper_notes",
        "field": "final_report_use",
        "allowed_value": "supporting_example",
        "counts_as_review": "yes",
        "meaning": "Paper supports a claim but should not anchor it.",
        "when_to_use": "Use for useful but less central examples.",
        "promotion_effect": "Good support row with caveats.",
    },
    {
        "table": "paper_notes",
        "field": "final_report_use",
        "allowed_value": "caveat_example",
        "counts_as_review": "yes",
        "meaning": "Paper mainly complicates or narrows a claim.",
        "when_to_use": "Use when it exposes limits or counterexamples.",
        "promotion_effect": "Useful for critical analysis; may weaken promotion.",
    },
    {
        "table": "paper_notes",
        "field": "final_report_use",
        "allowed_value": "exclude",
        "counts_as_review": "yes",
        "meaning": "Paper should not be used in final report synthesis.",
        "when_to_use": "Use for irrelevant, weak, or misclassified examples.",
        "promotion_effect": "Does not support promotion.",
    },
    {
        "table": "paper_notes",
        "field": "final_report_use",
        "allowed_value": "undecided",
        "counts_as_review": "yes",
        "meaning": "Reviewer has not decided report role.",
        "when_to_use": "Use when additional review is needed.",
        "promotion_effect": "Weak support until resolved.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "supports",
        "counts_as_review": "yes",
        "meaning": "Paper materially supports the linked synthesis claim.",
        "when_to_use": "Use when reviewed evidence directly supports the claim wording.",
        "promotion_effect": "Counts as support in acceptance criteria.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "partial_support",
        "counts_as_review": "yes",
        "meaning": "Paper supports a narrower or caveated version of the claim.",
        "when_to_use": "Use when the claim is directionally right but too broad.",
        "promotion_effect": "Counts as support, but manual_notes should carry caveat.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "weakens",
        "counts_as_review": "yes",
        "meaning": "Paper complicates or weakens the linked claim.",
        "when_to_use": "Use for contrary evidence, scope limits, or mismatch.",
        "promotion_effect": "Counts as weakening; blocks promotion while unresolved.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "contradicts",
        "counts_as_review": "yes",
        "meaning": "Paper directly contradicts the linked claim.",
        "when_to_use": "Use for clear counterexamples.",
        "promotion_effect": "Counts as weakening; should trigger claim revision.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "not_applicable",
        "counts_as_review": "yes",
        "meaning": "Paper should not be used for this claim.",
        "when_to_use": "Use when paper is in queue but does not bear on the claim.",
        "promotion_effect": "Reviewed but not support.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_claim_support",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Reviewer cannot decide claim relationship.",
        "when_to_use": "Use when further review is needed.",
        "promotion_effect": "Reviewed but not support.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "correct",
        "counts_as_review": "yes",
        "meaning": "Taxonomy assignment is acceptable for this claim.",
        "when_to_use": "Use when area/subarea supports the claim linkage.",
        "promotion_effect": "Helps taxonomy gates pass.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "too_broad",
        "counts_as_review": "yes",
        "meaning": "Claim/taxonomy grouping is overly broad for this paper.",
        "when_to_use": "Use when the paper fits only a narrower slice.",
        "promotion_effect": "Blocks taxonomy-sensitive promotion.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "too_narrow",
        "counts_as_review": "yes",
        "meaning": "Claim/taxonomy grouping misses broader relevance.",
        "when_to_use": "Use when paper spans more than assigned category.",
        "promotion_effect": "Requires caveat or taxonomy revision.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "wrong_area",
        "counts_as_review": "yes",
        "meaning": "Report-level area assignment is wrong.",
        "when_to_use": "Use for clear area mismatch.",
        "promotion_effect": "Blocks taxonomy-sensitive promotion.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "wrong_subarea",
        "counts_as_review": "yes",
        "meaning": "Subarea assignment is wrong but area may be acceptable.",
        "when_to_use": "Use for subarea mismatch.",
        "promotion_effect": "Blocks subarea claims and adds caveat to area claims.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_taxonomy_judgment",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Taxonomy relationship is unresolved.",
        "when_to_use": "Use when taxonomy needs another reviewer.",
        "promotion_effect": "Blocks taxonomy-sensitive promotion.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "not_applicable",
        "counts_as_review": "yes",
        "meaning": "Artifact check is irrelevant to this claim/paper.",
        "when_to_use": "Use for theory/position or non-artifact claims.",
        "promotion_effect": "Neutral.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "none",
        "counts_as_review": "yes",
        "meaning": "No artifact found.",
        "when_to_use": "Use after checking source links.",
        "promotion_effect": "Does not satisfy artifact gate.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "linked_unchecked",
        "counts_as_review": "yes",
        "meaning": "Artifact link exists but was not inspected.",
        "when_to_use": "Use as a temporary state.",
        "promotion_effect": "Does not satisfy artifact gate.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "live_checked",
        "counts_as_review": "yes",
        "meaning": "Artifact link was opened and is live.",
        "when_to_use": "Use after a live check.",
        "promotion_effect": "Counts toward artifact gate.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "runnable",
        "counts_as_review": "yes",
        "meaning": "Artifact appears runnable/reproducible.",
        "when_to_use": "Use after inspecting setup or examples.",
        "promotion_effect": "Counts toward artifact gate.",
    },
    {
        "table": "claim_overlay",
        "field": "manual_artifact_judgment",
        "allowed_value": "broken",
        "counts_as_review": "yes",
        "meaning": "Artifact link or repository is unusable.",
        "when_to_use": "Use after direct inspection.",
        "promotion_effect": "Counts as checked but weakens artifact claim.",
    },
    {
        "table": "area_overlay",
        "field": "manual_validated",
        "allowed_value": "yes",
        "counts_as_review": "yes",
        "meaning": "Paper validates assigned area/subarea and area claim use.",
        "when_to_use": "Use when assignment and evidence are clear.",
        "promotion_effect": "Supports area-level use.",
    },
    {
        "table": "area_overlay",
        "field": "manual_validated",
        "allowed_value": "partial",
        "counts_as_review": "yes",
        "meaning": "Paper partly validates area use but needs caveat.",
        "when_to_use": "Use for boundary papers.",
        "promotion_effect": "Supports area use with caveat.",
    },
    {
        "table": "area_overlay",
        "field": "manual_validated",
        "allowed_value": "no",
        "counts_as_review": "yes",
        "meaning": "Paper should not validate the assigned area/fault line.",
        "when_to_use": "Use for misclassified or irrelevant examples.",
        "promotion_effect": "Weakens area claim.",
    },
    {
        "table": "area_overlay",
        "field": "manual_validated",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Area validation is unresolved.",
        "when_to_use": "Use when more review is needed.",
        "promotion_effect": "Does not support promotion.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "method",
        "counts_as_review": "yes",
        "meaning": "Main contribution is an algorithm, architecture, model, or training method.",
        "when_to_use": "Use for mechanism-first papers.",
        "promotion_effect": "Helps contribution-mix analysis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "theory",
        "counts_as_review": "yes",
        "meaning": "Main contribution is formal analysis/proof.",
        "when_to_use": "Use for theory papers.",
        "promotion_effect": "Helps program-attention analysis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "system",
        "counts_as_review": "yes",
        "meaning": "Main contribution is infrastructure, serving, tooling, or integrated system.",
        "when_to_use": "Use for systems/agents workflows.",
        "promotion_effect": "Helps systems/agentic workload claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "dataset",
        "counts_as_review": "yes",
        "meaning": "Main contribution is data collection, dataset, or resource.",
        "when_to_use": "Use when data resource is central.",
        "promotion_effect": "Helps benchmark/data claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "benchmark",
        "counts_as_review": "yes",
        "meaning": "Main contribution is benchmark/evaluation suite.",
        "when_to_use": "Use for evaluation-package papers.",
        "promotion_effect": "Important for C04/C05 interpretation.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "analysis",
        "counts_as_review": "yes",
        "meaning": "Main contribution is empirical or conceptual analysis.",
        "when_to_use": "Use for diagnostic/measurement papers.",
        "promotion_effect": "Often supports caveats or fault lines.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "application",
        "counts_as_review": "yes",
        "meaning": "Main contribution is an applied use case.",
        "when_to_use": "Use when method novelty is secondary.",
        "promotion_effect": "Supports area breadth, not necessarily core method claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "survey_or_position",
        "counts_as_review": "yes",
        "meaning": "Main contribution is position, survey, or argument.",
        "when_to_use": "Use for position papers.",
        "promotion_effect": "Useful for context, not empirical support.",
    },
    {
        "table": "area_overlay",
        "field": "manual_primary_contribution_type",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Contribution type cannot be decided.",
        "when_to_use": "Use when review is inconclusive.",
        "promotion_effect": "Does not support contribution-type claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "none",
        "counts_as_review": "yes",
        "meaning": "No artifact found.",
        "when_to_use": "Use after checking.",
        "promotion_effect": "Weakens artifact claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "linked_unchecked",
        "counts_as_review": "yes",
        "meaning": "Artifact link exists but was not inspected.",
        "when_to_use": "Use as temporary state.",
        "promotion_effect": "Does not satisfy artifact inspection.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "live_checked",
        "counts_as_review": "yes",
        "meaning": "Artifact link is live.",
        "when_to_use": "Use after opening the link.",
        "promotion_effect": "Supports artifact visibility, not reproducibility.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "runnable",
        "counts_as_review": "yes",
        "meaning": "Artifact appears runnable or reproducible.",
        "when_to_use": "Use after inspecting setup/data/checkpoints.",
        "promotion_effect": "Strong artifact support.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "broken",
        "counts_as_review": "yes",
        "meaning": "Artifact is stale, private, or unusable.",
        "when_to_use": "Use after failed direct check.",
        "promotion_effect": "Weakens artifact claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_artifact_status",
        "allowed_value": "not_applicable",
        "counts_as_review": "yes",
        "meaning": "Artifact is irrelevant to paper type.",
        "when_to_use": "Use for pure theory/position papers.",
        "promotion_effect": "Neutral.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "positive",
        "counts_as_review": "yes",
        "meaning": "Results primarily strengthen the area/fault-line story.",
        "when_to_use": "Use for clear wins or validated results.",
        "promotion_effect": "Supports area synthesis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "negative",
        "counts_as_review": "yes",
        "meaning": "Results primarily show failures or limits.",
        "when_to_use": "Use for negative or cautionary papers.",
        "promotion_effect": "Supports caveats.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "mixed",
        "counts_as_review": "yes",
        "meaning": "Results are mixed across settings.",
        "when_to_use": "Use when paper should narrow a claim.",
        "promotion_effect": "Supports nuanced claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "theoretical",
        "counts_as_review": "yes",
        "meaning": "Result is mainly theoretical.",
        "when_to_use": "Use for theory/proof papers.",
        "promotion_effect": "Useful for program/theory synthesis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "benchmark_only",
        "counts_as_review": "yes",
        "meaning": "Result is mainly benchmark/data packaging.",
        "when_to_use": "Use for dataset/benchmark papers.",
        "promotion_effect": "Useful for evaluation landscape claims.",
    },
    {
        "table": "area_overlay",
        "field": "manual_result_character",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Result character cannot be decided.",
        "when_to_use": "Use when additional reading is needed.",
        "promotion_effect": "Does not support promotion.",
    },
    {
        "table": "area_overlay",
        "field": "manual_fault_line_relevance",
        "allowed_value": "headline",
        "counts_as_review": "yes",
        "meaning": "Paper is strong enough to anchor an area fault line.",
        "when_to_use": "Use sparingly for best examples.",
        "promotion_effect": "Candidate report example.",
    },
    {
        "table": "area_overlay",
        "field": "manual_fault_line_relevance",
        "allowed_value": "supporting",
        "counts_as_review": "yes",
        "meaning": "Paper supports but should not anchor the fault line.",
        "when_to_use": "Use for secondary examples.",
        "promotion_effect": "Supports area synthesis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_fault_line_relevance",
        "allowed_value": "caveat",
        "counts_as_review": "yes",
        "meaning": "Paper mainly adds a caveat or boundary condition.",
        "when_to_use": "Use for limitations, failures, or mixed evidence.",
        "promotion_effect": "Improves critical analysis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_fault_line_relevance",
        "allowed_value": "not_relevant",
        "counts_as_review": "yes",
        "meaning": "Paper should not be used for this area fault line.",
        "when_to_use": "Use for irrelevant/misclassified rows.",
        "promotion_effect": "Does not support area synthesis.",
    },
    {
        "table": "area_overlay",
        "field": "manual_fault_line_relevance",
        "allowed_value": "unclear",
        "counts_as_review": "yes",
        "meaning": "Fault-line relevance is unresolved.",
        "when_to_use": "Use when another review pass is needed.",
        "promotion_effect": "Does not support promotion.",
    },
]


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    fieldnames = [
        "table",
        "field",
        "allowed_value",
        "counts_as_review",
        "meaning",
        "when_to_use",
        "promotion_effect",
    ]
    write_csv(PROCESSED / "icml2026_manual_review_codebook.csv", ROWS, fieldnames)

    by_field: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in ROWS:
        by_field[(row["table"], row["field"])].append(row)

    lines = [
        "# ICML 2026 Manual Review Codebook",
        "",
        "Canonical value guide for paper notes and manual review overlays.",
        "Use these values when filling `data/manual/` files so downstream acceptance gates interpret the review consistently.",
        "",
        "## Quick Rules",
        "",
        "- Use `partial_support`, not `mixed`, for a claim that is directionally supportive but too broad.",
        "- Use `linked_unchecked`, `live_checked`, `runnable`, or `broken` for artifacts; avoid free-text artifact states in coded fields.",
        "- Put nuance, caveats, and direct evidence in `manual_notes` or `paper_note` rather than inventing new coded values.",
        "- A row can be reviewed but still not support promotion; `unclear`, `not_applicable`, `weakens`, and `contradicts` are valid reviewed outcomes.",
        "",
        "## Field Values",
        "",
    ]
    for (table, field), rows in sorted(by_field.items()):
        lines.extend(
            [
                f"### `{table}.{field}`",
                "",
                "| Value | Meaning | When to use | Promotion effect |",
                "| --- | --- | --- | --- |",
            ]
        )
        for row in rows:
            lines.append(
                f"| `{row['allowed_value']}` | {row['meaning']} | {row['when_to_use']} | {row['promotion_effect']} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Transfer Pattern",
            "",
            "1. Fill paper-note fields from the PDF/ICML page/repository.",
            "2. Rebuild the relevant overlay bridge.",
            "3. Copy only coded decisions into overlay fields.",
            "4. Put sentence-level evidence and caveats in `manual_notes`.",
            "5. Rebuild reviewed tables, progress, readiness, acceptance criteria, decision board, and validation.",
            "",
            "## Outputs",
            "",
            "- `data/processed/icml2026_manual_review_codebook.csv`",
            "- `reports/icml2026_manual_review_codebook.md`",
        ]
    )
    (REPORTS / "icml2026_manual_review_codebook.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {PROCESSED / 'icml2026_manual_review_codebook.csv'} ({len(ROWS)} rows)")
    print(f"Wrote {REPORTS / 'icml2026_manual_review_codebook.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
