"""Hand-authored teaching material for the public learning course."""

from __future__ import annotations


FOUNDATION_QUIZ = [
    {
        "question": "An area contains 10% of all papers and 15% of oral papers. What is its oral enrichment?",
        "options": ["0.67×", "1.0×", "1.5×", "5×"],
        "answer": 2,
        "explanation": "Enrichment divides oral share by paper share: 15% ÷ 10% = 1.5×.",
    },
    {
        "question": "A method improves benchmark accuracy. Which conclusion is safest?",
        "options": [
            "It is better in every real deployment",
            "It improved this benchmark under the reported setup",
            "It understands the task like a person",
            "Its mechanism is proven",
        ],
        "answer": 1,
        "explanation": "A benchmark result directly supports only the tested task, data, metric, and setup.",
    },
    {
        "question": "What is the main purpose of an ablation?",
        "options": [
            "Make a model larger",
            "Remove or change components to identify what causes the gain",
            "Collect more citations",
            "Replace the test set",
        ],
        "answer": 1,
        "explanation": "Ablations test whether the proposed component, rather than another change, explains an improvement.",
    },
    {
        "question": "A repository link is visible beside a paper. What has been established?",
        "options": [
            "The paper was independently reproduced",
            "All results can be regenerated",
            "A potentially relevant artifact is visible and still needs inspection",
            "The implementation is correct",
        ],
        "answer": 2,
        "explanation": "Visibility is useful for finding an artifact. Identity, contents, execution, and result agreement remain separate checks.",
    },
]


SYNTHESIS_QUIZ = [
    {
        "question": "Theory has high oral enrichment and lower public-attention enrichment. What follows?",
        "options": [
            "Theory is objectively better than other areas",
            "Program selection and platform attention emphasize different work",
            "The public dislikes mathematics",
            "Every theory oral is important",
        ],
        "answer": 1,
        "explanation": "The contrast describes two selection signals. It does not reveal quality or audience motivation by itself.",
    },
    {
        "question": "Why can multimodal research be large at ICML and underweight against nearby venues?",
        "options": [
            "The statements use different denominators",
            "One statement must be wrong",
            "Underweight means low quality",
            "Only oral papers are counted",
        ],
        "answer": 0,
        "explanation": "One claim describes share inside ICML; the other compares that share with a separate venue baseline.",
    },
    {
        "question": "Which comparison best connects agents and systems?",
        "options": [
            "Only parameter count",
            "Task success together with latency, tool failures, and cost",
            "Repository stars only",
            "Paper count only",
        ],
        "answer": 1,
        "explanation": "An agent is an end-to-end system. Capability and operational cost must be evaluated together.",
    },
    {
        "question": "Robotics has small paper share and high public attention. What is a good next step?",
        "options": [
            "Declare robotics the best field",
            "Inspect whether demos, artifacts, or task properties explain the attention contrast",
            "Ignore the paper share",
            "Assume every repository reproduces its paper",
        ],
        "answer": 1,
        "explanation": "An enrichment contrast is a reading lead. Paper-level inspection is how we investigate possible explanations.",
    },
]


AREA_LESSONS = {
    1: {
        "hook": "A model can produce a correct answer for the wrong reason. Post-training tries to make useful behavior more likely, while verification and search try to select better behavior at inference time.",
        "mental_model": "Think of a base model as a proposal generator. A reward or verifier supplies a score, policy optimization changes which proposals are likely, and test-time search spends additional computation choosing among them.",
        "workflow": ["Generate one or more candidate traces", "Score outcomes or intermediate steps", "Update the policy or select a candidate", "Test whether gains survive new tasks and larger compute budgets"],
        "formula_title": "Outcome-weighted policy update",
        "formula": "maximize  E[r(x, y)]  while limiting how far π moves from π₀",
        "formula_explanation": "The reward r favors useful outputs y for prompt x. A reference-policy constraint helps prevent a model from exploiting the reward in destructive ways.",
        "example_title": "Worked example: verifiable arithmetic",
        "example": ["The model produces four solution traces.", "A checker gives reward 1 only when the final answer is correct.", "Training increases the probability of rewarded traces.", "The key limitation: final-answer reward does not tell us whether the written reasoning is faithful."],
        "compare": "Traditional supervised fine-tuning imitates target answers. RL-style post-training optimizes a reward signal. Test-time search may improve answers without changing model weights.",
        "glossary": {"RLVR": "reinforcement learning with automatically verifiable rewards", "process reward": "a score for intermediate reasoning steps", "pass@k": "whether at least one of k attempts succeeds", "KL penalty": "a cost for moving too far from a reference policy"},
        "quiz": [
            {"question": "What does a final-answer verifier directly check?", "options": ["Whether every reasoning step is faithful", "Whether the final output satisfies a check", "Whether the task is socially useful", "Whether training data is unbiased"], "answer": 1, "explanation": "Outcome verification can establish correctness of the checked output, not faithfulness of every intermediate statement."},
            {"question": "What changes when we increase test-time compute without retraining?", "options": ["The training dataset", "The number of candidates or search steps used for an answer", "The tokenizer vocabulary", "The model license"], "answer": 1, "explanation": "Sampling, search, reflection, or verification can spend more inference computation while keeping weights fixed."},
            {"question": "Why constrain a policy near a reference model?", "options": ["To guarantee truth", "To limit unstable or reward-exploiting changes", "To remove evaluation", "To increase context length"], "answer": 1, "explanation": "Reference constraints control how aggressively reward optimization changes behavior; they do not guarantee truth."},
            {"question": "Which result would best support transfer beyond math tasks?", "options": ["Higher math reward", "Gains across open-ended tasks with different evaluators", "More generated tokens", "A larger training batch"], "answer": 1, "explanation": "Transfer requires evidence on tasks whose correctness cannot be checked in the same cheap way."},
        ],
    },
    2: {
        "hook": "A multimodal model should use what it sees, not merely produce a plausible sentence from language patterns.",
        "mental_model": "The system converts images, video, audio, or 3D observations into representations, aligns them with language, and then reasons or acts over the combined evidence.",
        "workflow": ["Encode visual or temporal observations", "Align observations with language or actions", "Fuse information across space and time", "Evaluate grounding, consistency, and robustness—not only answer accuracy"],
        "formula_title": "Grounded prediction",
        "formula": "prediction = f(text tokens, visual tokens, time, geometry)",
        "formula_explanation": "A convincing test changes or removes relevant visual evidence and checks whether the prediction changes appropriately.",
        "example_title": "Worked example: motion versus appearance",
        "example": ["Two training clips show the same object but different motion quality.", "An attribution method weights temporal regions rather than static pixels.", "The method ranks which clips influence generated motion.", "Human preference is helpful, but physical plausibility needs separate evaluation."],
        "compare": "Image classification asks what is present. Grounded reasoning asks which evidence supports an answer. Video and 3D additionally require temporal or spatial consistency.",
        "glossary": {"VLM": "a model that jointly processes vision and language", "grounding": "linking an answer to specific observed evidence", "temporal consistency": "maintaining coherent change through time", "distribution shift": "testing on conditions different from training"},
        "quiz": [
            {"question": "How can we test whether a VLM uses visual evidence?", "options": ["Ask a longer question", "Change the relevant image region and observe the answer", "Increase temperature", "Count model parameters"], "answer": 1, "explanation": "A controlled intervention on relevant visual evidence tests whether the answer depends on that evidence."},
            {"question": "Which metric is most specific to video?", "options": ["Temporal consistency", "Vocabulary size", "Training loss only", "Number of citations"], "answer": 0, "explanation": "Video evaluation must account for how content and motion evolve over time."},
            {"question": "A high caption score proves that a model understands 3D space. True?", "options": ["Yes", "No"], "answer": 1, "explanation": "Caption quality may come from language priors and does not establish spatial reasoning."},
            {"question": "What does motion attribution try to separate?", "options": ["Training and inference", "Temporal influence and static appearance", "Text and labels", "Accuracy and loss"], "answer": 1, "explanation": "It asks which data influences motion rather than simply influencing what the frame looks like."},
        ],
    },
    3: {
        "hook": "Theory asks not only whether a method works, but under which assumptions it must work, may work, or cannot work.",
        "mental_model": "Start with a mathematical setting, define the objective and assumptions, derive a guarantee or impossibility result, then test whether the predicted behavior appears outside the idealized model.",
        "workflow": ["State the objects, assumptions, and quantity of interest", "Prove a bound, convergence rate, or impossibility", "Identify how the result scales", "Check which real settings violate the assumptions"],
        "formula_title": "Generalization gap",
        "formula": "test error − training error",
        "formula_explanation": "A small training error alone is not enough. Theory often studies when performance on observed samples transfers to unseen data.",
        "example_title": "Worked example: delayed generalization",
        "example": ["A model quickly drives training error near zero.", "Test error remains high for many optimization steps.", "Weight decay gradually changes which solution is selected.", "A theorem predicts when test error should fall, but its linear assumptions must be checked before applying it to transformers."],
        "compare": "Empirical work estimates what happens in measured settings. Theory explains consequences of stated assumptions. Strong research often uses each to challenge the other.",
        "glossary": {"regret": "the accumulated gap from the best comparison decision", "convergence rate": "how quickly an error shrinks", "expressivity": "which functions a model class can represent", "assumption": "a condition under which a theorem is valid"},
        "quiz": [
            {"question": "A theorem is correct. Does it automatically describe a production LLM?", "options": ["Yes", "Only if its assumptions and scale meaningfully match", "Only if it has many equations", "Only if it is an oral"], "answer": 1, "explanation": "Correctness within a formal setting and applicability to a practical system are different questions."},
            {"question": "What is grokking?", "options": ["Immediate memorization and generalization", "Delayed improvement in generalization after fitting training data", "A graph algorithm", "A quantization method"], "answer": 1, "explanation": "Grokking refers to a long delay between fitting training data and improving on unseen data."},
            {"question": "Which result is an impossibility result?", "options": ["A faster optimizer", "A proof that a model class cannot solve a task under given conditions", "A higher benchmark score", "A larger dataset"], "answer": 1, "explanation": "Impossibility results define limits rather than proposing another empirical improvement."},
            {"question": "Why pair a proof with experiments?", "options": ["To replace assumptions", "To see whether predicted behavior appears beyond the exact formal case", "To guarantee causality", "To avoid baselines"], "answer": 1, "explanation": "Experiments can probe relevance beyond the theorem, though they do not extend the proof."},
        ],
    },
    4: {
        "hook": "A lower benchmark error is not automatically a scientific discovery, a useful molecule, or a safe clinical decision.",
        "mental_model": "Scientific ML combines a learning objective with domain structure, uncertainty, and an external validity test such as physical constraints, expert review, simulation, or laboratory measurement.",
        "workflow": ["Define the scientific object and target", "Encode useful structure or invariance", "Predict or generate with uncertainty", "Validate against physical, biological, or clinical evidence"],
        "formula_title": "Prediction with uncertainty",
        "formula": "output = estimate ± calibrated uncertainty",
        "formula_explanation": "A useful scientific model should communicate when it is uncertain, especially outside the conditions represented in training data.",
        "example_title": "Worked example: protein backbone generation",
        "example": ["Generate a coarse global topology.", "Condition finer structural scales on that topology.", "Decode atomic backbone coordinates.", "Check geometry and designability—but remember that structural validity does not establish biological function."],
        "compare": "A benchmark asks whether predictions match held-out labels. Scientific validation may additionally require conservation laws, plausible mechanisms, wet-lab tests, or clinical outcomes.",
        "glossary": {"equivariance": "a predictable output change when the input is transformed", "calibration": "agreement between confidence and observed accuracy", "surrogate model": "a fast approximation to an expensive process", "OOD": "data outside the training distribution"},
        "quiz": [
            {"question": "A generated protein has plausible geometry. What remains open?", "options": ["Whether it contains atoms", "Biological function and laboratory behavior", "Whether geometry exists", "Whether a model ran"], "answer": 1, "explanation": "Structural plausibility is only one stage of biological validation."},
            {"question": "Why is uncertainty important in scientific ML?", "options": ["It makes plots colorful", "Decisions may be costly when inputs differ from training", "It guarantees discovery", "It replaces validation"], "answer": 1, "explanation": "Uncertainty helps identify cases where a model may not be trustworthy."},
            {"question": "Which is strongest evidence for a clinical claim?", "options": ["Training accuracy", "Validation on appropriate patients and outcomes", "Repository stars", "A synthetic example"], "answer": 1, "explanation": "Clinical claims need evidence that matches the intended population and outcome."},
            {"question": "What does multiscale generation provide?", "options": ["Only more parameters", "A way to coordinate global structure and local detail", "Guaranteed biological function", "A privacy mechanism"], "answer": 1, "explanation": "Coarse-to-fine models connect global topology with detailed structure."},
        ],
    },
    5: {
        "hook": "Better learning can come from changing the data, asking causal questions, or coordinating across separate data owners—not only from changing the model.",
        "mental_model": "First identify what information is observed, where it lives, and what question is being asked. Prediction, intervention, continual adaptation, and federated coordination require different assumptions.",
        "workflow": ["Audit data quality and collection", "Choose prediction, causal, continual, or federated objective", "Control leakage, forgetting, and client differences", "Evaluate under realistic shifts and constraints"],
        "formula_title": "Prediction versus intervention",
        "formula": "P(Y | X=x)  is not generally  P(Y | do(X=x))",
        "formula_explanation": "Observing X and actively changing X are different. Confounding can make predictive associations misleading for interventions.",
        "example_title": "Worked example: continual robot learning",
        "example": ["A policy learns task A, then task B.", "Fine-tuning on B may overwrite behavior for A.", "A small replay buffer mixes prior examples into training.", "Measure both new-task learning and old-task forgetting across realistic task sequences."],
        "compare": "Data-centric work improves the training evidence. Causal work targets interventions. Continual learning manages change over time. Federated learning coordinates data that cannot be centralized.",
        "glossary": {"confounder": "a variable influencing both a proposed cause and outcome", "replay": "reusing older examples during later training", "client heterogeneity": "differences among federated participants", "data valuation": "estimating how much examples contribute"},
        "quiz": [
            {"question": "A variable predicts an outcome. Does changing it necessarily change the outcome?", "options": ["Yes", "No; causal assumptions or interventions are needed", "Only with deep learning", "Only with more data"], "answer": 1, "explanation": "Prediction can be driven by confounding rather than a causal effect."},
            {"question": "What does replay address in continual learning?", "options": ["Catastrophic forgetting", "Image resolution", "Network latency", "Causal discovery"], "answer": 0, "explanation": "Older examples help preserve previous behavior while learning new tasks."},
            {"question": "Why is client heterogeneity important?", "options": ["Every client has identical data", "Different clients may have different distributions and resources", "It guarantees privacy", "It removes communication"], "answer": 1, "explanation": "Real federated systems are rarely identically distributed or equally capable."},
            {"question": "Which metric pair best evaluates continual learning?", "options": ["New-task performance and forgetting", "Stars and visits", "Parameters and citations", "Only final loss"], "answer": 0, "explanation": "A system must learn new tasks while retaining useful old behavior."},
        ],
    },
    6: {
        "hook": "A method is not efficient merely because one kernel runs faster. The entire workload must deliver acceptable quality at lower time, memory, energy, or cost.",
        "mental_model": "Trace the full path from model weights and hardware through training or serving to user-visible latency and output quality. Bottlenecks move when batch size, sequence length, or hardware changes.",
        "workflow": ["Choose the real workload and hardware", "Measure a trustworthy baseline", "Change precision, architecture, cache, kernel, or schedule", "Report end-to-end cost together with quality regressions"],
        "formula_title": "End-to-end throughput",
        "formula": "useful outputs / total wall-clock time",
        "formula_explanation": "A local speedup matters only if it improves the full pipeline without unacceptable capability loss.",
        "example_title": "Worked example: KV-cache reduction",
        "example": ["Autoregressive generation stores key and value states for earlier tokens.", "Longer contexts increase cache memory.", "Pruning or quantizing the cache reduces memory traffic.", "Measure latency and memory across sequence lengths, then check whether answer quality falls."],
        "compare": "Optimization research may improve the update rule. Systems research asks whether the implementation produces reliable end-to-end gains on real hardware.",
        "glossary": {"KV cache": "stored attention states for previously generated tokens", "quantization": "representing numbers with fewer bits", "throughput": "completed work per unit time", "MoE": "a mixture-of-experts model that activates selected components"},
        "quiz": [
            {"question": "A kernel is 2× faster. Is the application 2× faster?", "options": ["Always", "Only if that kernel dominates end-to-end time and other costs stay similar", "Never", "Only on a laptop"], "answer": 1, "explanation": "Amdahl-style bottlenecks mean local speedups do not directly determine full-system speed."},
            {"question": "Why report quality with efficiency?", "options": ["Faster output may be worse", "Quality determines GPU temperature", "It removes baselines", "It guarantees fairness"], "answer": 0, "explanation": "Efficiency gains can trade away accuracy, reasoning, calibration, or safety."},
            {"question": "What grows with autoregressive context length?", "options": ["KV-cache storage", "The number of repository stars", "The training dataset", "The license"], "answer": 0, "explanation": "Attention states from prior tokens must be retained unless compressed or discarded."},
            {"question": "Which evaluation is strongest?", "options": ["One batch size on one GPU", "Multiple realistic workloads, hardware settings, and quality checks", "A theoretical FLOP count only", "A screenshot"], "answer": 1, "explanation": "System behavior can change substantially across workload and hardware conditions."},
        ],
    },
    7: {
        "hook": "A safety measure changes the system being measured. Training against a detector can produce safer behavior—or teach the model how to evade detection.",
        "mental_model": "Define the threat actor, assets, capabilities, and failure cost. Then test both ordinary behavior and adaptive attacks, including whether defenses create new incentives.",
        "workflow": ["Specify a concrete threat model", "Measure attacks and false alarms", "Adapt the attacker to the defense", "Evaluate downstream harm, privacy, fairness, and governance consequences"],
        "formula_title": "Detector trade-off",
        "formula": "risk depends on missed harms and false alarms",
        "formula_explanation": "A detector that flags everything catches attacks but becomes unusable. Evaluation must measure both sides under realistic conditions.",
        "example_title": "Worked example: deception probes",
        "example": ["A probe detects activation patterns associated with deceptive behavior.", "Training penalizes high probe scores.", "The policy may become honest, lose capability, or change representations to avoid the probe.", "Inspect behavior, task reward, and representation drift—not the probe score alone."],
        "compare": "Robustness asks how behavior changes under perturbation. Privacy asks what information is exposed. Governance asks how rules and institutions manage risks. They overlap but need different evidence.",
        "glossary": {"threat model": "explicit assumptions about attacker goals and capabilities", "red teaming": "actively searching for failures", "false positive": "safe behavior incorrectly flagged", "adaptive attack": "an attack redesigned with knowledge of the defense"},
        "quiz": [
            {"question": "A detector score falls after training. What else should be checked?", "options": ["Only the detector again", "Behavior, capability, and alternative signs of evasion", "Paper length", "Model color"], "answer": 1, "explanation": "The model may have become safer, weaker, or better at hiding from that particular detector."},
            {"question": "What makes a threat model useful?", "options": ["It says the system is dangerous", "It names assets, attacker capabilities, and failure conditions", "It uses a large model", "It has no assumptions"], "answer": 1, "explanation": "Concrete assumptions make security evidence interpretable and challengeable."},
            {"question": "Why measure false positives?", "options": ["A defense that blocks safe behavior may be unusable", "They increase citations", "They guarantee fairness", "They replace attacks"], "answer": 0, "explanation": "Operational safety includes the cost of incorrectly blocking legitimate behavior."},
            {"question": "Does one benchmark cover real-world safety?", "options": ["Yes", "No; risks and attackers change across deployments", "Only if accuracy is high", "Only for open models"], "answer": 1, "explanation": "Safety evidence is conditional on the tested threat model, environment, and population."},
        ],
    },
    8: {
        "hook": "An agent is more than a language model: prompts, tools, memory, environment state, and recovery logic jointly determine performance.",
        "mental_model": "Treat the agent as a control loop: observe state, plan, choose a tool, inspect the result, update memory, and decide whether to continue or recover.",
        "workflow": ["Observe the task and environment", "Plan and select a tool", "Execute and inspect feedback", "Recover, revise, or finish under cost and safety limits"],
        "formula_title": "Agent utility",
        "formula": "task success − cost − unsafe actions − unrecovered errors",
        "formula_explanation": "Success alone can hide expensive search, brittle tools, or unacceptable actions.",
        "example_title": "Worked example: academic figure agent",
        "example": ["Retrieve relevant figure references.", "Plan which concepts and relationships to show.", "Render a draft and critique readability and faithfulness.", "Revise, while measuring whether each agent component adds value."],
        "compare": "A base-model benchmark isolates model capability. An agent benchmark evaluates the combined model, scaffolding, tools, and environment.",
        "glossary": {"tool routing": "choosing which external operation to call", "scaffolding": "prompts and control logic around a model", "trajectory": "the sequence of observations and actions", "contamination": "test tasks leaking into training or examples"},
        "quiz": [
            {"question": "An agent improves after adding a better search tool. What improved directly?", "options": ["The model weights", "The complete agent system", "The training data", "The theorem"], "answer": 1, "explanation": "System capability can improve without any change in the underlying model."},
            {"question": "Which metric exposes brittle recovery?", "options": ["Success after tool failure", "Parameter count", "Paper share", "Token vocabulary"], "answer": 0, "explanation": "Injecting or observing failures reveals whether an agent can recognize and repair mistakes."},
            {"question": "Why report cost per successful task?", "options": ["Success may require excessive calls or tokens", "It proves safety", "It measures citations", "It removes latency"], "answer": 0, "explanation": "Two agents with equal success can differ greatly in practical efficiency."},
            {"question": "What should an ablation remove?", "options": ["A component such as memory or reflection", "The test set", "All baselines", "The problem statement"], "answer": 0, "explanation": "Component ablations help identify which part of the scaffold causes a gain."},
        ],
    },
    9: {
        "hook": "When relationships and symmetry matter, treating every input as an unrelated flat vector throws away useful structure.",
        "mental_model": "Represent objects as nodes and relations as edges. Repeated message passing lets each node combine local information while respecting permutation or geometric symmetries.",
        "workflow": ["Choose nodes, edges, and features", "Send and aggregate messages", "Update node or graph representations", "Test expressivity and generalization beyond training graph sizes"],
        "formula_title": "Message-passing update",
        "formula": "hᵢ′ = update(hᵢ, aggregate({message(hᵢ, hⱼ, eᵢⱼ)}))",
        "formula_explanation": "Each node updates its representation using messages from neighbors. The aggregation should not depend on arbitrary node ordering.",
        "example_title": "Worked example: shortest-path learning",
        "example": ["Nodes represent locations and edges carry distances.", "Messages propagate current distance estimates.", "Repeated layers imitate relaxation steps in a shortest-path algorithm.", "Success on small graphs does not prove generalization to larger graphs or longer paths."],
        "compare": "Sequence models rely on order. Graph models rely on relations. Geometric models additionally encode how outputs should transform under rotations or translations.",
        "glossary": {"equivariance": "outputs transform predictably when inputs transform", "invariance": "an output remains unchanged under a transformation", "message passing": "neighbor-to-neighbor information exchange", "oversmoothing": "node representations becoming too similar"},
        "quiz": [
            {"question": "Why use permutation-invariant aggregation?", "options": ["Node numbering should not change the graph meaning", "It increases graph size", "It guarantees shortest paths", "It removes edges"], "answer": 0, "explanation": "Reordering node identifiers should not change a graph-level result."},
            {"question": "A GNN fits every training graph. Has it learned the algorithm?", "options": ["Necessarily", "Not unless it generalizes under relevant size and structure changes", "Only if it is deep", "Only with attention"], "answer": 1, "explanation": "Memorizing finite instances differs from learning a reusable procedure."},
            {"question": "What does one message-passing layer usually access?", "options": ["Immediate-neighbor information", "Every graph in the dataset", "Only labels", "No structure"], "answer": 0, "explanation": "Information travels roughly one graph hop per standard layer."},
            {"question": "Which task especially benefits from rotational equivariance?", "options": ["Molecular geometry", "Alphabetical sorting", "Citation counting", "Tokenization"], "answer": 0, "explanation": "A rotated molecule should lead to predictably rotated geometric outputs rather than a different physical interpretation."},
        ],
    },
    10: {
        "hook": "Generative models learn how data is distributed so they can produce, transform, or score new samples—not merely assign a label.",
        "mental_model": "Diffusion gradually corrupts data and learns to reverse that process. Flow methods learn a continuous transport from a simple distribution to the data distribution.",
        "workflow": ["Choose a simple starting distribution", "Learn a denoising score or transport field", "Run a multi-step or distilled sampler", "Evaluate quality, diversity, control, speed, and consistency separately"],
        "formula_title": "Denoising step",
        "formula": "xₜ₋₁ = xₜ + model-predicted correction + controlled noise",
        "formula_explanation": "The sampler repeatedly moves a noisy state toward regions that resemble training data.",
        "example_title": "Worked example: same seed, different training split",
        "example": ["Train two diffusion models on different samples from one data distribution.", "Give both models the same initial noise.", "Their outputs can remain surprisingly similar.", "Random-matrix analysis asks how shared data statistics and finite-sample differences explain agreement."],
        "compare": "Likelihood, perceptual quality, diversity, prompt adherence, physical validity, and sampling speed answer different questions. No single metric captures them all.",
        "glossary": {"score": "the direction toward higher data density", "guidance": "steering samples toward a condition", "flow matching": "learning a continuous velocity field between distributions", "mode collapse": "failing to represent important kinds of outputs"},
        "quiz": [
            {"question": "What is reversed during diffusion sampling?", "options": ["A gradual noising process", "A graph traversal", "Federated averaging", "A policy update"], "answer": 0, "explanation": "Diffusion models learn to undo progressive corruption."},
            {"question": "High visual quality proves high diversity. True?", "options": ["Yes", "No"], "answer": 1, "explanation": "A model can produce beautiful but repetitive samples."},
            {"question": "Why reuse the same noise seed across models?", "options": ["To compare how learned sampling maps transform the same starting point", "To guarantee identical output", "To increase training data", "To remove conditioning"], "answer": 0, "explanation": "A shared seed controls the starting randomness and makes model differences easier to study."},
            {"question": "Which evaluation belongs to controllable generation?", "options": ["Whether output follows the requested condition", "Only parameter count", "Only training loss", "Only wall-clock time"], "answer": 0, "explanation": "Control requires measuring whether requested attributes actually appear without destroying quality or diversity."},
        ],
    },
    11: {
        "hook": "Reinforcement learning studies sequential decisions whose consequences may arrive later, under uncertainty and limited experience.",
        "mental_model": "An agent observes a state, chooses an action using a policy, receives reward, and transitions to a new state. Learning must assign credit across time.",
        "workflow": ["Define states, actions, transitions, and rewards", "Collect online experience or use an offline dataset", "Estimate values or improve a policy", "Evaluate return, robustness, sample cost, and generalization"],
        "formula_title": "Discounted return",
        "formula": "Gₜ = rₜ + γrₜ₊₁ + γ²rₜ₊₂ + …",
        "formula_explanation": "The discount γ controls how strongly later rewards influence the current decision.",
        "example_title": "Worked example: more computation per action",
        "example": ["Keep the policy parameter count fixed.", "Allow the policy to perform more internal update steps before acting.", "Test whether it solves longer-horizon tasks.", "Report wall-clock cost as well as reward, because internal computation is not free."],
        "compare": "Supervised learning receives target labels. RL receives consequences of actions. Offline RL must learn without freely exploring beyond a fixed behavior dataset.",
        "glossary": {"policy": "a rule for choosing actions", "value": "expected future return", "offline RL": "learning from a fixed interaction dataset", "credit assignment": "deciding which earlier actions caused later outcomes"},
        "quiz": [
            {"question": "What makes RL sequential?", "options": ["Actions change future states and rewards", "It always uses language", "It has no data", "It requires robots"], "answer": 0, "explanation": "Current decisions affect which situations and rewards become available later."},
            {"question": "What is a major offline RL challenge?", "options": ["Evaluating unseen actions without safely trying them", "Too much online exploration", "No reward definition", "Always having perfect coverage"], "answer": 0, "explanation": "A fixed dataset may poorly cover actions proposed by a new policy."},
            {"question": "More decision-time compute with fixed weights tests what?", "options": ["Whether computation itself expands usable policy capability", "Whether the dataset is larger", "Whether parameters were added", "Whether rewards disappear"], "answer": 0, "explanation": "It separates internal computation from parameter count."},
            {"question": "Why can reward design dominate results?", "options": ["The agent optimizes what is measured, including shortcuts", "Rewards never affect policies", "Rewards are labels only", "It changes graph edges"], "answer": 0, "explanation": "A poorly aligned reward can make benchmark success diverge from intended behavior."},
        ],
    },
    12: {
        "hook": "Embodied intelligence must connect perception and language to actions that obey time, geometry, contact, and safety constraints.",
        "mental_model": "A robot policy observes the world, maintains task-relevant memory, predicts or reasons about consequences, and produces actions through a controller.",
        "workflow": ["Observe multimodal state", "Retrieve history or update memory", "Plan or predict outcomes", "Execute safely and recover from changed physical conditions"],
        "formula_title": "History-dependent policy",
        "formula": "actionₜ ~ π(observationₜ, memoryₜ)",
        "formula_explanation": "Tasks involving occlusion, repeated actions, or long instructions cannot always be solved from the current camera frame alone.",
        "example_title": "Worked example: hidden-object manipulation",
        "example": ["A robot sees an object placed in one of several drawers.", "The drawer is later closed, so the current image is ambiguous.", "Memory must preserve the earlier location and relevant action history.", "Compare memory designs across temporal, spatial, object, and procedural tasks—not one demo."],
        "compare": "A VLM answers about observations. A VLA policy maps observations and language to actions. A world model predicts how the environment may change after an action.",
        "glossary": {"VLA": "a vision-language-action model", "world model": "a model of environment dynamics", "behavior cloning": "imitating actions from demonstrations", "sim-to-real": "transferring behavior from simulation to physical systems"},
        "quiz": [
            {"question": "Why does a hidden-object task require memory?", "options": ["The current observation no longer contains the needed location", "The robot needs more parameters", "The reward is always zero", "The image is high resolution"], "answer": 0, "explanation": "Relevant information was observed earlier and must persist after occlusion."},
            {"question": "What distinguishes a VLA policy from a VLM?", "options": ["It produces physical actions as well as processing vision and language", "It has no vision", "It cannot use language", "It is always smaller"], "answer": 0, "explanation": "VLA models close the loop from multimodal input to action."},
            {"question": "A compelling robot video proves broad generalization. True?", "options": ["Yes", "No; task diversity, resets, intervention, and failure rates matter"], "answer": 1, "explanation": "A selected demonstration can hide narrow conditions and unsuccessful trials."},
            {"question": "Why compare several memory types?", "options": ["Tasks require different temporal, spatial, object, or procedural information", "One design always wins", "Memory removes perception", "It guarantees safety"], "answer": 0, "explanation": "RoboMME-style results suggest that useful memory depends strongly on task requirements."},
        ],
    },
}


# Conservative, abstract-based previews for the two comparison papers in each
# area. These are teaching summaries, not substitutes for reading the papers.
PAPER_CASES = {
    "How much can language models memorize?": {
        "problem": "Memorization measurements often mix up information about a particular dataset with knowledge that generalizes beyond it.",
        "approach": "Separate unintended dataset memorization from generalization, then estimate model capacity after removing the generalization component.",
        "evidence": "Hundreds of transformers from 500K to 1.5B parameters trained across increasing dataset sizes.",
        "takeaway": "The study reports capacity scaling and a transition from filling capacity with memorization toward greater generalization.",
        "caution": "Capacity estimates depend on the formal separation and experimental regime; they are not a universal measure of what a model understands.",
    },
    "Maximum Likelihood Reinforcement Learning": {
        "problem": "Expected-reward RL can provide almost no learning signal on binary tasks where a model rarely succeeds.",
        "approach": "Derive a compute-indexed objective from pass@k likelihood that moves from ordinary RL toward maximum likelihood as sampling compute grows.",
        "evidence": "Policy-gradient experiments across several correctness-based domains against standard RL and GRPO.",
        "takeaway": "The reported method improves both single-attempt and multi-attempt success in the evaluated settings.",
        "caution": "The derivation focuses on binary correctness; open-ended rewards and evaluator errors need separate study.",
    },
    "Holi-Spatial: Evolving Video Streams into Holistic 3D Spatial Intelligence": {
        "problem": "Existing spatial datasets are small, manually curated, and poorly matched to the diversity of raw web video.",
        "approach": "Automatically turn video into reconstructed 3D scenes, geometric annotations, grounding examples, and spatial question-answer pairs.",
        "evidence": "A 4-million-example resource, reconstruction-quality comparisons, and VLM fine-tuning on spatial reasoning tasks.",
        "takeaway": "The pipeline aims to make detailed 3D supervision scalable while improving downstream spatial reasoning.",
        "caution": "Automatically produced labels can inherit reconstruction errors; dataset scale does not by itself establish physical understanding.",
    },
    "Bad Seeing or Bad Thinking? Rewarding Perception for Multimodal Reasoning": {
        "problem": "When a VLM fails, ordinary rewards do not reveal whether perception or later reasoning caused the error.",
        "approach": "Split perception from reasoning and route structured rewards using a blindfolded-reasoning proxy and modality-aware credit assignment.",
        "evidence": "Free-form vision-language tasks designed to measure whether targeted perception rewards improve both stages.",
        "takeaway": "The work argues that more precise credit assignment can reduce the trade-off between seeing accurately and reasoning well.",
        "caution": "Proxy verification may still reward incomplete visual evidence, so intervention-based grounding tests remain important.",
    },
    "Equivalence of Context and Parameter Updates in Modern Transformer Blocks": {
        "problem": "Earlier context-as-weight-update theory covers simple transformers but not the gated, normalized, or expert-based blocks used today.",
        "approach": "Construct exact implicit weight patches and characterize when inner and outer functions permit context effects to be represented as parameter changes.",
        "evidence": "Analytical proofs for Gemma-style blocks followed by a constructive extension to multilayer and varied transformer designs.",
        "takeaway": "The framework offers a common mathematical view of how prompts induce token-dependent effective computation.",
        "caution": "Exact representational equivalence does not show that models learn, store, or use context in the same way during real training.",
    },
    "Non-Euclidean Gradient Descent Operates at the Edge of Stability": {
        "problem": "Edge-of-stability behavior is common in deep learning, while standard theory is centered on Euclidean gradient descent.",
        "approach": "Define geometry-aware directional smoothness and generalized sharpness for optimizers operating under other norms.",
        "evidence": "Analysis plus neural-network experiments covering infinity-norm descent, coordinate methods, spectral descent, and Muon-like updates.",
        "takeaway": "Progressive sharpening and threshold oscillation appear to extend beyond ordinary gradient descent.",
        "caution": "A shared spectral description does not imply identical optimization dynamics or downstream behavior across optimizers.",
    },
    "dnaHNet: A Scalable and Hierarchical Foundation Model for Genomic Sequence Learning": {
        "problem": "Genomic tokenizers can break biological motifs, while nucleotide-level modeling makes long sequences expensive.",
        "approach": "Learn differentiable, hierarchical chunks directly from raw nucleotides and model the resulting latent sequence autoregressively.",
        "evidence": "Prokaryotic pretraining, scaling and speed comparisons, plus zero-shot protein-variant and gene-essentiality tasks.",
        "takeaway": "Adaptive compression is reported to improve efficiency while recovering useful biological hierarchy.",
        "caution": "Predictive gains and discovered patterns require biological validation before being interpreted as mechanistic insight.",
    },
    "Orthogonal Concept Erasure for Diffusion Models": {
        "problem": "Fast parameter editing can erase a target concept while damaging unrelated generation capability.",
        "approach": "Use closed-form orthogonal transformations to change neuron direction while preserving magnitude and broader angular geometry.",
        "evidence": "Single- and multi-concept erasure experiments, including large batches of target concepts and preservation measurements.",
        "takeaway": "The method reports faster, more selective erasure than additive editing approaches.",
        "caution": "This is intentionally a boundary case: erasure quality, safety goals, and hidden semantic leakage require more than aggregate generation metrics.",
    },
    "Midtraining Bridges Pretraining and Posttraining Distributions": {
        "problem": "Specialized data inserted between pretraining and post-training often helps, but the conditions that make it work are unclear.",
        "approach": "Treat midtraining as a distributional bridge and vary domain distance, insertion time, and mixture weight in controlled training runs.",
        "evidence": "Code and mathematics domains, in-domain performance, forgetting measurements, and timing-mixture interactions.",
        "takeaway": "Bridging is most useful for distant target domains, and late specialization may be constrained by reduced model plasticity.",
        "caution": "The result concerns selected domains and training schedules; it does not establish one universal recipe for data mixtures.",
    },
    "Expressivity-Efficiency Tradeoffs for Hybrid Sequence Models": {
        "problem": "Hybrid attention and state-space models promise both expressivity and efficiency without a clear account of when the combination is necessary.",
        "approach": "Prove limitations for non-hybrid models on synthetic tasks and construct compact hybrids that avoid the same memory-parameter trade-off.",
        "evidence": "Formal results for selective copying and associative recall plus learned-model experiments on length and distribution shifts.",
        "takeaway": "Hybrid structure can solve some tasks with substantially smaller working memory and model size.",
        "caution": "Synthetic separations reveal mechanisms but may not predict end-to-end advantages on natural workloads.",
    },
    "POET-X: Memory-efficient LLM Training by Scaling Orthogonal Transformation": {
        "problem": "Spectrum-preserving training can improve stability but incur too much matrix-computation and memory overhead at large scale.",
        "approach": "Rework orthogonal-equivalence transformations into a more scalable optimizer implementation.",
        "evidence": "Billion-parameter pretraining, throughput and memory measurements, and comparison with optimizers that exceed a single H100’s memory.",
        "takeaway": "The reported implementation retains stability benefits while making the approach practical at larger scale.",
        "caution": "A single-hardware demonstration should be followed by matched compute, quality, and multi-platform evaluation.",
    },
    "FlashSinkhorn: IO-Aware Entropic Optimal Transport on GPU": {
        "problem": "GPU Sinkhorn solvers repeatedly move large interaction matrices through high-bandwidth memory.",
        "approach": "Rewrite updates as attention-like reductions and fuse tiled Triton kernels so data can be streamed through on-chip memory.",
        "evidence": "Point-cloud optimal-transport workloads on A100 GPUs and downstream optimization comparisons.",
        "takeaway": "IO-aware reformulation reports large forward and end-to-end speedups with linear-memory operation.",
        "caution": "The largest kernel speedup is not automatically the gain for every transport cost, hardware platform, or complete application.",
    },
    "Position: The Alignment Community is Unintentionally Building a Censor’s Toolkit": {
        "problem": "Techniques created to suppress harmful output can also enable political censorship and informational control.",
        "approach": "Map alignment mechanisms to dual-use misuse cases and propose mitigations for intentional abuse.",
        "evidence": "A position argument grounded in existing techniques, reported cases, adoption patterns, and political risk scenarios.",
        "takeaway": "Safety evaluation should include who controls a mechanism and how it may be deliberately repurposed.",
        "caution": "A position paper frames risks and recommendations; its claims require different evidence than a controlled technical benchmark.",
    },
    "Position: AI/ML Deepfake Research is Misaligned with AI Generated Non-Consensual Intimate Imagery (AIG-NCII)": {
        "problem": "Deepfake research often prioritizes truth and authenticity while neglecting harms to people depicted without consent.",
        "approach": "Audit influential research through a subject-centered harm model and recommend threat models aligned with non-consensual imagery abuse.",
        "evidence": "A landscape analysis of highly cited work and comparison between viewer-centered and subject-centered interventions.",
        "takeaway": "Authenticity detection alone may not mitigate dignity, consent, and safety harms to affected subjects.",
        "caution": "Work in this domain requires safeguards and expert partnerships; technical detection metrics cannot stand in for harm reduction.",
    },
    "$\\tau^2$-Bench: Evaluating Conversational Agents in a Dual-Control Environment": {
        "problem": "Most agent benchmarks let only the AI change the environment, unlike support tasks where users must also take actions.",
        "approach": "Model a shared telecom environment where agent and user have tools, with generated tasks and a state-constrained user simulator.",
        "evidence": "Dual-control task performance and ablations separating reasoning failures from communication and coordination errors.",
        "takeaway": "Agent performance drops when success requires reliably guiding another actor through state-changing actions.",
        "caution": "Simulator fidelity and telecom coverage limit how directly the result transfers to real users and other domains.",
    },
    "Agent0-VL: Exploring Self-Evolving Agent for Tool-Integrated Vision-Language Reasoning": {
        "problem": "Text-only self-evaluation can hallucinate when checking visual reasoning and cannot ground every correction in observable evidence.",
        "approach": "Combine solver and verifier roles with tools, structured critique, self-repair, and reinforcement learning in one VLM.",
        "evidence": "Chart, geometry, and visual-science reasoning evaluations against the underlying Qwen-VL model.",
        "takeaway": "Tool-grounded self-verification is reported to improve the agent without external reward annotation.",
        "caution": "Self-evaluation and test tools may share blind spots; independent verification and tool-failure tests remain necessary.",
    },
    "Towards Hierarchy–Uniformity Equilibrium: Recovering Semantic Depth in Hypergraph Contrastive Learning": {
        "problem": "Contrastive learning can spread hypergraph embeddings so uniformly that higher-order semantic hierarchy disappears.",
        "approach": "Separate spectral frequencies and attach a learned prototype tree to balance local discrimination with global hierarchy.",
        "evidence": "A theoretical frequency-separation argument and comparisons across 15 datasets and 17 baselines.",
        "takeaway": "The method aims to preserve semantic depth without losing useful instance-level distinction.",
        "caution": "The hierarchy is learned under specific objectives and assumptions; interpretability of the recovered structure still needs inspection.",
    },
    "PhenoBrain: Phenotype-Conditioned Long-Range Communication for Multi-Modal Brain Network Analysis": {
        "problem": "The same brain connectivity pattern can imply different things under different phenotype contexts, which late fusion may miss.",
        "approach": "Condition long-range graph routing and attention directly on subject phenotype information.",
        "evidence": "Two datasets built from open neuroimaging sources and comparisons on neuropsychiatric prediction.",
        "takeaway": "Injecting phenotype into the communication mechanism is reported to outperform treating it as an auxiliary feature.",
        "caution": "Predictive performance does not establish clinical validity, causal brain mechanisms, or generalization across populations.",
    },
    "High-accuracy sampling for diffusion models and log-concave distributions": {
        "problem": "Existing high-accuracy diffusion samplers can require a number of steps that grows polynomially as target error shrinks.",
        "approach": "Develop algorithms whose accuracy dependence is polylogarithmic under stated score-estimation and distribution assumptions.",
        "evidence": "Complexity theorems for general, Lipschitz, intrinsic-dimensional, and log-concave settings.",
        "takeaway": "The analysis provides an exponential improvement in error dependence over earlier theoretical guarantees.",
        "caution": "Iteration complexity assumes sufficiently accurate score access and does not directly measure wall-clock quality for modern image models.",
    },
    "High-accuracy and dimension-free sampling with diffusions": {
        "problem": "Numerically solving diffusion dynamics at high accuracy often needs many small discretization steps tied to ambient dimension.",
        "approach": "Combine low-degree approximation with collocation to solve the diffusion equation more efficiently.",
        "evidence": "A theoretical iteration bound with polylogarithmic accuracy dependence and dimension entering only through effective support radius.",
        "takeaway": "The solver establishes a route to high-accuracy guarantees without explicit ambient-dimension dependence.",
        "caution": "The guarantee concerns approximate score access and mathematical error, which may differ from perceptual quality and GPU runtime.",
    },
    "Learning Human-Robot Collaboration via Heterogeneous-Agent Lyapunov Policy Optimization": {
        "problem": "Independent learning by humans and robots can oscillate because the two agents follow different objectives and response dynamics.",
        "approach": "Project decentralized policy gradients so a Lyapunov measure of parameter disagreement contracts at every step.",
        "evidence": "Stability analysis, simulations, and physical humanoid-robot collaboration experiments.",
        "takeaway": "Certified contraction is reported to improve robustness and generalization in difficult collaboration cases.",
        "caution": "Parameter-space stability is not the same as human safety, comfort, or successful transfer to broader interaction settings.",
    },
    "Distributional Inverse Reinforcement Learning": {
        "problem": "Conventional inverse RL often recovers one reward or matches only mean return, hiding uncertainty and risk preferences.",
        "approach": "Model distributions over rewards and returns using stochastic-dominance constraints and risk-sensitive policy learning.",
        "evidence": "Convergence analysis plus synthetic, neurobehavioral, and MuJoCo imitation experiments.",
        "takeaway": "Distributional reward representations are reported to improve risk-aware imitation across varied settings.",
        "caution": "Recovered reward distributions remain model-dependent explanations of behavior, not direct measurements of human intent.",
    },
    "From Pixels to Tokens: A Systematic Study of Latent Action Supervision for Vision-Language-Action Models": {
        "problem": "VLA systems use incompatible latent-action designs without a controlled comparison of what each representation contributes.",
        "approach": "Compare four integrations that either regularize visual trajectories or unify action targets under one VLA baseline.",
        "evidence": "Long-horizon reasoning, motor-coordination, and mixed-data experiments across image- and action-based latent supervision.",
        "takeaway": "Different formulations suit different tasks, with direct discrete-token supervision reported as the strongest overall choice.",
        "caution": "The formulation-task relationship may change with the base policy, robot embodiment, data quality, and deployment horizon.",
    },
    "XR-1: Towards Versatile Vision-Language-Action Models via Learning Unified Vision-Motion Representations": {
        "problem": "VLA models struggle to produce precise actions while sharing knowledge across robots, demonstrations, and visual domains.",
        "approach": "Learn discrete codes joining visual dynamics with motion, then use staged self-supervised, cross-embodiment, and task-specific training.",
        "evidence": "More than 12,000 physical rollouts across six robot embodiments and over 120 manipulation tasks.",
        "takeaway": "Unified vision-motion codes are reported to improve cross-robot performance and robustness to novel visual conditions.",
        "caution": "Large rollout counts strengthen evaluation, but task selection, intervention, safety, and reproducibility still require inspection.",
    },
}
